version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: python main.py
        volumes:
            - .:/app
        working_dir: /app
        ports:
          - "8080:8080"